services:
  - type: web
    name: esg-intelligence-backend
    env: python
    buildCommand: pip install -r requirements.txt && python src/init_database.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: "*" 